export const Author: string;
export const Categories: string;
export const Content: string;
export const Extra: string;
export const FeaturedImage: string;
export const GenericBlock: string;
export const MainContent: string;
export const Metadata: string;
export const ShareButtons: string;
export const ShareButtonsSeconday: string;
// export const Tags: string;
export const Title: string;
